sudo: false
language: csharp
solution: IO.Ably.sln
install:
  - nuget restore ./src/IO.Ably.Travis.sln
script:
  - xbuild /p:Configuration='Release' ./src/IO.Ably.Travis.sln
  - mono ./tools/xunit-runners/tools/xunit.console.exe ./src/IO.Ably.Tests/bin/Release/IO.Ably.Tests.dll -parallel none -noappdomain -verbose